export { default as Home } from './Home'
export { default as Cart } from './Cart'
export { default as Categories } from './Categories'
export { default as Collections } from './Collections'
export { default as Offers } from './Offers'
export { default as Profile } from './Profile'
export { default as Orders } from './Orders'
export { default as Search } from './Search'
export { default as Address } from './Address'
export { default as AccountDetails } from './AccountDetails'
export {default as Product} from './Product'
export { default as Wishlist } from './Wishlist'
export {default as SosCallBack} from './SosCallBack'