export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminCollection } from './AdminCollection'
export {default as AdminCategory} from './AdminCategory'
export {default as AdminOffer} from './AdminOffer'
export { default as AdminOrders } from './AdminOrders'   
export { default as AdminProduct } from './AdminProduct'
export { default as AdminSettings } from './AdminSettings'
export { default as AdminCustomers } from './AdminCustomers'
export { default as AdminReviews } from './AdminReviews'