export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminCollection } from './AdminCollection'
export {default as AdminCategory} from './AdminCategory'
export {default as AdminOffer} from './AdminOffer'
export { default as AdminOrders } from './AdminOrders'   
export { default as AdminProduct } from './AdminProduct'
export { default as AdminSettings } from './AdminSettings'
export { default as AdminCustomers } from './AdminCustomers'
export { default as AdminReviews } from './AdminReviews'
export {default as AdminAddProduct} from './AdminAddProduct'
export { default as AdminUpdateProduct } from './AdminUpdateProduct'
export { default as AdminAddCollection } from './AdminAddCollection'
export { default as AdminUpdateCollection } from './AdminUpdateCollection'
export { default as AdminAddOffer } from './AdminAddOffer'
export { default as AdminUpdateOffer } from './AdminUpdateOffer'
export { default as AdminInventory } from './AdminInventory'